yarnPath: ".yarn/releases/yarn-berry.cjs"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_TOKEN}"

npmScopes:
  daangn:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "gatsby-source-prismic@*": 
    dependencies:
      "gatsby-plugin-image": "*"
  "gatsby-plugin-prismic-previews@*": 
    dependencies:
      "gatsby-plugin-image": "*"
