nmMode: hardlinks-global

nodeLinker: node-modules

# See https://github.com/yarnpkg/berry/issues/4615#issuecomment-1180840428
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-4.2.2.cjs
